from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np
import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing


@dataclass(frozen=True)
class HWComponents:
    level: pd.Series
    trend: pd.Series
    seasonal: pd.Series
    resid: pd.Series


def add_cyclical_time_features(index: pd.DatetimeIndex) -> pd.DataFrame:
    hour = index.hour.to_numpy()
    dow = index.dayofweek.to_numpy()

    hour_sin = np.sin(2 * math.pi * hour / 24.0)
    hour_cos = np.cos(2 * math.pi * hour / 24.0)
    dow_sin = np.sin(2 * math.pi * dow / 7.0)
    dow_cos = np.cos(2 * math.pi * dow / 7.0)

    return pd.DataFrame(
        {
            "hour_sin": hour_sin,
            "hour_cos": hour_cos,
            "dow_sin": dow_sin,
            "dow_cos": dow_cos,
        },
        index=index,
    )


def seasonal_period_for_scale(scale: str) -> int:
    # Heuristic seasonalities per aggregated frequency.
    # Hourly -> daily cycle; Daily -> weekly; Weekly -> yearly; Monthly -> yearly; Quarterly -> yearly.
    return {
        "hourly": 24,
        "daily": 7,
        "weekly": 52,
        "monthly": 12,
        "quarterly": 4,
    }[scale]


def add_lag_features(
    df: pd.DataFrame,
    *,
    cols: list[str],
    lags: list[int],
) -> pd.DataFrame:
    """
    Add lagged versions of selected columns.

    Example: cols=["global_active_power"], lags=[1,24] adds:
      global_active_power_lag1, global_active_power_lag24
    """
    out = df.copy()
    for c in cols:
        if c not in out.columns:
            continue
        for lag in lags:
            out[f"{c}_lag{int(lag)}"] = out[c].shift(int(lag))
    return out


def default_target_lags_for_scale(scale: str) -> list[int]:
    # Strong autoregressive memory by resolution.
    # hourly: previous hour, previous day, previous week
    # daily: previous day, previous week, previous month-ish
    # weekly/monthly/quarterly: short + seasonal memories
    return {
        "hourly": [1, 24, 168],
        "daily": [1, 7, 30],
        "weekly": [1, 4, 12],
        "monthly": [1, 3, 12],
        "quarterly": [1, 2, 4],
    }[scale]


def add_rolling_features(
    df: pd.DataFrame,
    *,
    cols: list[str],
    windows: list[int],
) -> pd.DataFrame:
    """
    Add rolling mean/std features using prior observations (shifted by 1).
    """
    out = df.copy()
    for c in cols:
        if c not in out.columns:
            continue
        s = out[c]
        for w in windows:
            wi = int(w)
            out[f"{c}_rollmean_{wi}"] = s.rolling(window=wi, min_periods=wi).mean().shift(1)
            out[f"{c}_rollstd_{wi}"] = s.rolling(window=wi, min_periods=wi).std().shift(1)
    return out


def fit_holt_winters_components(
    y_train: pd.Series,
    seasonal_periods: int,
) -> tuple[object, HWComponents]:
    model = ExponentialSmoothing(
        y_train.astype(float),
        trend="add",
        seasonal="add",
        seasonal_periods=seasonal_periods,
        initialization_method="estimated",
    )
    res = model.fit(optimized=True)

    # In-sample component estimates (aligned to y_train index)
    # statsmodels stores these as numpy arrays; align carefully.
    level = pd.Series(res.level, index=y_train.index, name="hw_level")
    # statsmodels exposes "trend" (not "slope") in newer versions
    trend = pd.Series(res.trend, index=y_train.index, name="hw_trend")
    seasonal = pd.Series(res.season, index=y_train.index, name="hw_seasonal")
    fitted = pd.Series(res.fittedvalues, index=y_train.index, name="hw_fitted")
    resid = (y_train - fitted).rename("hw_resid")

    return res, HWComponents(level=level, trend=trend, seasonal=seasonal, resid=resid)


def hw_components_one_step_ahead_features(
    y_train: pd.Series,
    y_full_index: pd.DatetimeIndex,
    scale: str,
) -> pd.DataFrame:
    """
    Build Holt-Winters component features for supervised learning without leakage by predicting y(t)
    from components at time t-1 (one-step lag).

    Returns a dataframe indexed by y_full_index with columns:
    hw_level_lag1, hw_trend_lag1, hw_seasonal_lag1, hw_resid_lag1

    For timestamps beyond the training window, components are generated by extending the final state
    of the fitted model deterministically (residuals set to 0 for future).
    """
    sp = seasonal_period_for_scale(scale)
    res, comps = fit_holt_winters_components(y_train=y_train, seasonal_periods=sp)

    # Build components for the whole horizon (train + test) by manual extension.
    # We extend level/trend with last slope; seasonal repeats last seasonal cycle.
    n_total = len(y_full_index)
    n_train = len(y_train)
    h = n_total - n_train

    level_all = np.empty(n_total, dtype=float)
    trend_all = np.empty(n_total, dtype=float)
    seasonal_all = np.empty(n_total, dtype=float)
    resid_all = np.empty(n_total, dtype=float)

    level_all[:n_train] = comps.level.to_numpy()
    trend_all[:n_train] = comps.trend.to_numpy()
    seasonal_all[:n_train] = comps.seasonal.to_numpy()
    resid_all[:n_train] = comps.resid.to_numpy()

    if h > 0:
        last_level = float(comps.level.iloc[-1])
        last_trend = float(comps.trend.iloc[-1])

        # Use the last full seasonal cycle if available; otherwise repeat last value.
        if n_train >= sp:
            last_cycle = comps.seasonal.iloc[-sp:].to_numpy()
        else:
            last_cycle = np.repeat(float(comps.seasonal.iloc[-1]), sp)

        for i in range(h):
            t = n_train + i
            level_all[t] = last_level + (i + 1) * last_trend
            trend_all[t] = last_trend
            seasonal_all[t] = last_cycle[i % sp]
            resid_all[t] = 0.0

    df = pd.DataFrame(
        {
            "hw_level": level_all,
            "hw_trend": trend_all,
            "hw_seasonal": seasonal_all,
            "hw_resid": resid_all,
        },
        index=y_full_index,
    )

    # Lag by 1 step to be safe for next-step prediction
    df = df.shift(1)
    df = df.rename(columns={c: f"{c}_lag1" for c in df.columns})
    return df
